/**
 * @file Estilos para la pantalla de juego. Define todos los componentes visuales.
 * @module jugando.styles
 */
import { Dimensions, StyleSheet } from "react-native";

// Para que la partida sea épicamente responsiva
const { width: ancho, height: alto } = Dimensions.get("window");

const BORDE_RADIO_BOTON = ancho * 0.0556;
const TAMANIO_ICONO_BOTON = ancho * 0.1;
const TAMANIO_TEMPORIZADOR = ancho * 0.15;

export const estilos = StyleSheet.create({
    contenedor: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: alto * 0.07,
    },
    fondo: {
    width: "100%",
    height: "100%",
    },
    superposicion: {
    backgroundColor: "rgba(38, 37, 34, 0.7)",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    },
    contenedorTexto: {
    position: "absolute",
    width: "80%",
    top: "21%",
    justifyContent: "center",
    alignItems: "center",
    },
    texto: {
    color: "white",
    fontSize: ancho * 0.09,
    fontFamily: "Corben",
    textAlign: "center",
    paddingHorizontal: ancho * 0.05,
    },
    contenedorRol: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    top: "35%",
    flexDirection: "column",
    },
    contenedorTextoRol: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    minHeight: alto * 0.1,
    paddingHorizontal: ancho * 0.05,
    },
    textoRol: {
    fontSize: ancho * 0.1,
    color: "white",
    fontFamily: "Corben",
    textAlign: "center",
    lineHeight: ancho * 0.12,
    paddingVertical: alto * 0.005,
    includeFontPadding: true,
    },
    imagenRol: {
    width: ancho * 0.35,
    height: ancho * 0.35,
    marginBottom: alto * 0.05,
    },
    nombreRol: {
    textAlign: "center",
    fontSize: ancho * 0.12,
    fontFamily: "Corben",
    fontWeight: "bold",
    },
    textoInicio: {
    color: "white",
    fontSize: ancho * 0.1,
    fontFamily: "Corben",
    textAlign: "center",
    top: "127%",
    paddingHorizontal: ancho * 0.05,
    },
    contenedorBotones: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingHorizontal: ancho * 0.10,
    },
    botonHabilidad: {
    flex: 1,
    backgroundColor: "#262522",
    height: alto * 0.13,
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: BORDE_RADIO_BOTON,
    borderTopRightRadius: BORDE_RADIO_BOTON,
    maxWidth: "45%",
    marginRight: ancho * 0.12,
    },
    botonChat: {
    flex: 1,
    backgroundColor: "#262522",
    height: alto * 0.07,
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: BORDE_RADIO_BOTON,
    borderTopRightRadius: BORDE_RADIO_BOTON,
    maxWidth: "45%",
    marginLeft: ancho * 0.02,
    },
    iconoBoton: {
    width: TAMANIO_ICONO_BOTON,
    height: TAMANIO_ICONO_BOTON,
    marginBottom: ancho * 0.02,
    },
    textoBoton: {
    color: "white",
    fontSize: ancho * 0.05,
    fontWeight: "bold",
    textAlign: "center",
    },
    contenedorBarraSuperior: {
    position: "absolute",
    top: alto * 0.06,
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#262522",
    paddingVertical: alto * 0.03,
    paddingHorizontal: ancho * 0.04,
    },
    seccionBarraSuperiorIzquierda: {
    flex: 1,
    alignItems: "flex-start",
    },
    seccionBarraSuperiorCentro: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    },
    seccionBarraSuperiorDerecha: {
    flex: 1,
    alignItems: "flex-end",
    },
    contenedorBarraSuperiorItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: ancho * 0.02,
    },
    iconoBarraSuperior: {
    width: ancho * 0.1,
    height: ancho * 0.1,
    borderRadius: ancho * 0.02,
    },
    textoBarraSuperiorContainer: {
    flexDirection: "column",
    },
    textoBarraSuperiorTitulo: {
    color: "white",
    fontSize: ancho * 0.04,
    fontWeight: "bold",
    },
    textoBarraSuperiorSub: {
    color: "white",
    fontSize: ancho * 0.03,
    fontWeight: "bold",
    opacity: 0.9,
    },
    contenedorCirculo: {
    position: "absolute",
    top: "56%",
    left: "50%",
    alignItems: "center",
    justifyContent: "center",
    },
    contenedorJugador: {
    position: "absolute",
    alignItems: 'center',
    },
    contenedorImagenCirculo: {
    borderRadius: 50,
    overflow: "hidden",
    justifyContent: 'center',
    alignItems: 'center',
    },
    imagenCirculo: {
    width: "100%",
    height: "100%",
    },
    contenedorVotos: {
    position: 'absolute',
    bottom: -alto * 0.025,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: ancho * 0.005,
    },
    barraVoto: {
    width: ancho * 0.008,
    height: alto * 0.015,
    backgroundColor: 'black',
    borderRadius: ancho * 0.002,
    },
    contenedorTemporizador: {
    position: "absolute",
    top: alto * 0.2,
    left: ancho * 0.05,
    zIndex: 2,
    },
    circuloTemporizador: {
    width: TAMANIO_TEMPORIZADOR,
    height: TAMANIO_TEMPORIZADOR,
    borderRadius: TAMANIO_TEMPORIZADOR / 2,
    backgroundColor: "#262522",
    justifyContent: "center",
    alignItems: "center",
    },
    textoTemporizador: {
    color: "white",
    fontSize: ancho * 0.05,
    fontWeight: "bold",
    },
    contenedorBotonesDerecha: {
    position: "absolute",
    top: alto * 0.2,
    right: ancho * 0.05,
    zIndex: 2,
    gap: ancho * 0.02,
    },
    botonAccion: {
    backgroundColor: "#262522",
    paddingVertical: alto * 0.02,
    paddingHorizontal: ancho * 0.06,
    borderRadius: ancho * 0.07,
    alignItems: "center",
    minWidth: ancho * 0.33,
    },
    botonVotar: {
    backgroundColor: "#262522",
    },
    contenedorChat: {
    position: "absolute",
    zIndex: 9999,
    left: ancho * 0.05,
    right: ancho * 0.05,
    bottom: 0,
    height: alto * 0.85,
    backgroundColor: "#262522",
    borderTopLeftRadius: ancho * 0.05,
    borderTopRightRadius: ancho * 0.05,
    padding: ancho * 0.04,
    borderWidth: ancho * 0.002,
    elevation: 50,
    shadowColor: "#262522",
    shadowOffset: { width: 0, height: alto * 0.003 },
    shadowOpacity: 0.5,
    shadowRadius: ancho * 0.02,
    },
    botonCerrarChat: {
    position: "absolute",
    top: alto * 0.02,
    right: ancho * 0.04,
    zIndex: 99999,
    padding: ancho * 0.02,
    backgroundColor: "#262522",
    borderRadius: ancho * 0.015,
    minWidth: ancho * 0.08,
    minHeight: ancho * 0.08,
    justifyContent: "center",
    alignItems: "center",
    },
    textoCerrarChat: {
    color: "white",
    fontSize: ancho * 0.07,
    fontWeight: "bold",
    fontFamily: "Corben",
    includeFontPadding: true,
    textAlignVertical: "center",
    marginBottom: -alto * 0.005,
    },
    tituloChat: {
    color: "white",
    fontSize: ancho * 0.07,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: alto * 0.02,
    fontFamily: "Corben",
    },
    separadorChat: {
    height: 1,
    backgroundColor: "white",
    marginVertical: alto * 0.02,
    },
    contenedorMensajesChat: {
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingBottom: alto * 0.02,
    },
    mensajeChat: {
    color: "white",
    fontSize: ancho * 0.04,
    marginBottom: alto * 0.015,
    fontFamily: "Corben",
    lineHeight: ancho * 0.05,
    includeFontPadding: true,
    },
    contenedorEntradaChat: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: alto * 0.02,
    },
    entradaChat: {
    flex: 1,
    height: alto * 0.07,
    borderWidth: ancho * 0.002,
    borderColor: "white",
    backgroundColor: "#262522",
    borderRadius: ancho * 0.02,
    paddingHorizontal: ancho * 0.03,
    color: "white",
    fontSize: ancho * 0.04,
    fontFamily: "Corben",
    },
    botonEnviarChat: {
    backgroundColor: "green",
    height: alto * 0.07,
    justifyContent: "center",
    paddingHorizontal: ancho * 0.04,
    borderRadius: ancho * 0.02,
    borderWidth: ancho * 0.002,
    marginLeft: ancho * 0.02,
    },
    textoBotonEnviarChat: {
    color: "white",
    fontWeight: "bold",
    fontSize: ancho * 0.04,
    fontFamily: "Corben",
    },
    contenedorHabilidad: {
    position: "absolute",
    zIndex: 9999,
    left: ancho * 0.05,
    right: ancho * 0.05,
    bottom: 0,
    height: alto * 0.6,
    backgroundColor: "#262522",
    borderTopLeftRadius: ancho * 0.05,
    borderTopRightRadius: ancho * 0.05,
    padding: ancho * 0.04,
    borderWidth: ancho * 0.002,
    elevation: 50,
    shadowColor: "#262522",
    shadowOffset: { width: 0, height: alto * 0.003 },
    shadowOpacity: 0.5,
    shadowRadius: ancho * 0.02,
    },
    botonCerrarHabilidad: {
    position: "absolute",
    top: alto * 0.02,
    right: ancho * 0.04,
    zIndex: 99999,
    padding: ancho * 0.02,
    backgroundColor: "#262522",
    borderRadius: ancho * 0.015,
    minWidth: ancho * 0.08,
    minHeight: ancho * 0.08,
    justifyContent: "center",
    alignItems: "center",
    },
    textoCerrarHabilidad: {
    color: "white",
    fontSize: ancho * 0.07,
    fontWeight: "bold",
    fontFamily: "Corben",
    includeFontPadding: true,
    textAlignVertical: "center",
    marginBottom: -alto * 0.005,
    },
    contenedorTituloHabilidad: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: alto * 0.02,
    },
    iconoHabilidadPopup: {
    width: ancho * 0.12,
    height: ancho * 0.12,
    marginRight: ancho * 0.02,
    },
    tituloHabilidad: {
    color: "white",
    fontSize: ancho * 0.07,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "Corben",
    },
    separadorHabilidad: {
    height: 1,
    backgroundColor: "white",
    marginVertical: alto * 0.02,
    },
    contenedorInfoHabilidad: {
    flexGrow: 1,
    justifyContent: "flex-start",
    paddingBottom: alto * 0.02,
    },
    textoHabilidad: {
    color: "white",
    fontSize: ancho * 0.05,
    marginBottom: alto * 0.015,
    fontFamily: "Corben",
    lineHeight: ancho * 0.06,
    includeFontPadding: true,
    },
    textoRecuerda: {
    color: "white",
    fontSize: ancho * 0.045,
    marginTop: alto * 0.02,
    fontFamily: "Corben",
    lineHeight: ancho * 0.055,
    includeFontPadding: true,
    },
    contenedorError: {
    position: 'absolute',
    top: alto * 0.08,
    alignSelf: 'center',
    backgroundColor: '#ff4444',
    paddingVertical: alto * 0.02,
    paddingHorizontal: ancho * 0.05,
    borderRadius: alto * 0.03,
    zIndex: 1000,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { 
        width: ancho * 0.005, 
        height: alto * 0.005 
    },
    shadowOpacity: 0.25,
    shadowRadius: alto * 0.005,
    maxWidth: ancho * 0.9,
    minHeight: alto * 0.06,
    alignItems: 'center',
    justifyContent: 'center',
    },
    textoError: {
    color: 'white',
    fontFamily: 'Corben',
    fontSize: alto * 0.022,
    textAlign: 'center',
    lineHeight: alto * 0.030,
    includeFontPadding: false,
    textAlignVertical: 'center',
    },
});